// Generated by Arabiki64 V1.0
// By Buu342

// Model convenience macro
#define MODEL_MyModel (&mdl_MyModel)

// Mesh data
#define MESHCOUNT_MyModel 1

#define MESH_MyModel_None 0

// Animation data
#define ANIMATIONCOUNT_MyModel 0



// Custom combine mode to allow mixing primitive and vertex colors
#ifndef G_CC_PRIMLITE
    #define G_CC_PRIMLITE SHADE,0,PRIMITIVE,0,0,0,0,PRIMITIVE
#endif


/*********************************
              Models
*********************************/

static Vtx vtx_MyModel_None[] = {
    {-50, 0, 0, 0, 0, 1024, 0, -127, 0, 255}, /* 0 */
    {50, 0, 0, 0, 1024, 1024, 0, -127, 0, 255}, /* 1 */
    {50, 0, 100, 0, 1024, 0, 0, -127, 0, 255}, /* 2 */
    {-50, 0, 100, 0, 0, 0, 0, -127, 0, 255}, /* 3 */
};

static Gfx gfx_MyModel_None[] = {
    gsSPVertex(vtx_MyModel_None+0, 4, 0),
    gsDPSetCycleType(G_CYC_1CYCLE),
    gsDPSetRenderMode(G_RM_AA_ZB_OPA_SURF, G_RM_AA_ZB_OPA_SURF2),
    gsDPSetCombineMode(G_CC_MODULATEIDECALA, G_CC_MODULATEIDECALA),
    gsDPSetTextureFilter(G_TF_BILERP),
    gsSPClearGeometryMode(0xFFFFFFFF),
    gsSPSetGeometryMode(G_SHADE | G_ZBUFFER | G_CULL_BACK | G_SHADING_SMOOTH | G_LIGHTING),
    gsDPLoadTextureBlock(tex_inercia, G_IM_FMT_RGBA, G_IM_SIZ_16b, 32, 32, 0, G_TX_MIRROR, G_TX_MIRROR, 5, 5, G_TX_NOLOD, G_TX_NOLOD),
    gsDPPipeSync(),
    gsSP2Triangles(0, 1, 2, 0, 0, 2, 3, 0),
    gsSPEndDisplayList(),
};


/*********************************
          Animation Data
*********************************/


/*********************************
        Sausage64 Structs
*********************************/

static s64Mesh meshes_MyModel[] = {
    {"None", gfx_MyModel_None},
};

static s64Animation anims_MyModel[] = {
};

static s64ModelData mdl_MyModel = {1, 0, meshes_MyModel, anims_MyModel};